CREATE TABLE CAR
(
    ID    SERIAL PRIMARY KEY,
    TYPE  VARCHAR(255),
    MODEL VARCHAR(255),
    COLOR TEXT
);
INSERT INTO CAR (TYPE, MODEL, COLOR)
VALUES ('sport', 'BMW', 'black');
SELECT *
FROM CAR;
UPDATE
    CAR
SET TYPE = 'cargo';
DELETE
FROM CAR;